---
version: '3'
services:
  db:
    image: "postgres:9.4"
    environment:
      - POSTGRES_PASSWORD=example

  tests:
    image: ruby:3.1
    working_dir: /work
    links:
      - db
    volumes:
      - ./:/work
    command: >
      bash -c "
        gem install bundler:2.2.33;
        bundle install;
        bundle exec rake spec
      "
